import Head from 'next/head'

export default function Home () {
  return (
    <>
      <Head>
        <title>Netflix Clone</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1 className='text-white text-center text-2xl'>Netflix Clone</h1>
      </main>
    </>
  )
}
